version: '3.1'
services:
  mongo:
    image: mongo
    network_mode: bridge
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: myUserAdmin