spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: file_system
      port: 27017
      host: localhost
      auto-index-creation: true
  cloud:
    config:
      enabled: false

job:
  scanJobPath: "f:/1"
  scanFixedRate: 60000